# Generated by Django 3.2.6 on 2021-10-17 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='titel',
            new_name='title',
        ),
    ]
